alpha: 0.0003
beta: 0.0003
gamma: 0.99
n_actions: 4
max_size: 1000000
tau: 0.005
layer1_size: 256
layer2_size: 256
batch_size: 256
reward_scale: 2
checkpoint_dir: "SAC/SelfMade/tmp/checkpoints"
log_dir: "runs/hockey_sac_training"
n_games: 20000
resume_training: False
opponent_update_interval: 20
win_rate_threshold: 0.6